name: BTC Mail Bot

on:
  schedule:
    - cron: '0 15 * * *'   # 16:00 w Polsce (UTC+1)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repo
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instaluj requests
        run: pip install requests

      - name: Uruchom bota
        run: python btc_tracker.py
